// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpcmcrbfihccafwaiefs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwY21jcmJmaWhjY2Fmd2FpZWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MjUxMjUsImV4cCI6MjA2NjIwMTEyNX0.PBzCqPhkh7U_B4Jqsi_YycchAvLhCj5GrvOycksXlW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});